/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    klienten_identitaet: KlientenIdentitaet;
    klienten_operativ: KlientenOperativ;
    touren: Touren;
    gdpr_audit_log: GdprAuditLog;
    bedarfe: Bedarfe;
    angehoerige_identitaet: AngehoerigeIdentitaet;
    angebote: Angebote;
    zahlungen: Zahlungen;
    abos: Abo;
    praeventionsempfehlungen: Praeventionsempfehlungen;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    klienten_identitaet: KlientenIdentitaetSelect<false> | KlientenIdentitaetSelect<true>;
    klienten_operativ: KlientenOperativSelect<false> | KlientenOperativSelect<true>;
    touren: TourenSelect<false> | TourenSelect<true>;
    gdpr_audit_log: GdprAuditLogSelect<false> | GdprAuditLogSelect<true>;
    bedarfe: BedarfeSelect<false> | BedarfeSelect<true>;
    angehoerige_identitaet: AngehoerigeIdentitaetSelect<false> | AngehoerigeIdentitaetSelect<true>;
    angebote: AngeboteSelect<false> | AngeboteSelect<true>;
    zahlungen: ZahlungenSelect<false> | ZahlungenSelect<true>;
    abos: AbosSelect<false> | AbosSelect<true>;
    praeventionsempfehlungen: PraeventionsempfehlungenSelect<false> | PraeventionsempfehlungenSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'disponent' | 'pflegekraft' | 'angehoeriger' | 'admin' | 'plattform_admin';
  tenantId?: string | null;
  totpSecret?: string | null;
  totpEnabled?: boolean | null;
  dienstName?: string | null;
  einzugsGeo?: {
    lat?: number | null;
    lng?: number | null;
  };
  einzugsRadiusKm?: number | null;
  einwilligungAt?: string | null;
  einwilligungVersion?: string | null;
  suchendeTyp?: ('angehoerige' | 'patient' | 'sozialdienst') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "klienten_identitaet".
 */
export interface KlientenIdentitaet {
  id: string;
  pseudonymId: string;
  tenantId: string;
  externalId?: string | null;
  vorname?: string | null;
  nachname?: string | null;
  adresse?: string | null;
  telefon?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "klienten_operativ".
 */
export interface KlientenOperativ {
  id: string;
  pseudonymId: string;
  tenantId: string;
  geo: {
    lat: number;
    lng: number;
  };
  pflegegrad?: number | null;
  leistungen?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  qualifikation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  zeitfenster: {
    von: number;
    bis: number;
  };
  dauerMin?: number | null;
  kostentraegerArt?: ('gesetzlich' | 'privat') | null;
  krankenversicherer?: string | null;
  bezugspflege?: string | null;
  status?: ('aktiv' | 'pausiert' | 'beendet') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "touren".
 */
export interface Touren {
  id: string;
  tenantId: string;
  datum: string;
  pflegekraftId: string;
  pflegekraftQualifikation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  start: {
    lat: number;
    lng: number;
  };
  ende?: {
    lat?: number | null;
    lng?: number | null;
  };
  startZeit?: number | null;
  einsaetze?:
    | {
        pseudonymId: string;
        geo: {
          lat: number;
          lng: number;
        };
        zeitfenster: {
          von: number;
          bis: number;
        };
        dauerMin?: number | null;
        grundzeitMin?: number | null;
        qualifikation?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        ankunft?: number | null;
        probe?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gdpr_audit_log".
 */
export interface GdprAuditLog {
  id: string;
  timestamp: string;
  request_type: 'RIGHT_TO_BE_FORGOTTEN' | 'RIGHT_TO_ACCESS' | 'IMPORT' | 'CONTACT_RELEASE';
  identity_hash: string;
  pepper_version: string;
  former_pseudonym_id?: string | null;
  status?: ('SUCCESS' | 'FAILURE') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bedarfe".
 */
export interface Bedarfe {
  id: string;
  pseudonymId: string;
  geo: {
    lat: number;
    lng: number;
  };
  pflegegrad?: number | null;
  leistungen?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  qualifikation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  kostentraegerArt?: ('gesetzlich' | 'privat') | null;
  krankenversicherer?: string | null;
  bundesland?: string | null;
  stadtteil?: string | null;
  alter?: number | null;
  wohnsituation?: ('alleinlebend' | 'gemeinschaft') | null;
  startDatum?: string | null;
  abwesenheiten?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  abwesenheitErlaeuterung?: string | null;
  besonderheiten?: string | null;
  leistungsauswahl?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  zeitfenster: {
    von: number;
    bis: number;
  };
  dauerMin?: number | null;
  grundzeitMin?: number | null;
  express?: boolean | null;
  status?: ('offen' | 'in_bearbeitung' | 'vergeben' | 'abgesagt') | null;
  matchingTenants?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  selectedTenantId?: string | null;
  deadlineAt?: string | null;
  firstResponseAt?: string | null;
  uebernommenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angehoerige_identitaet".
 */
export interface AngehoerigeIdentitaet {
  id: string;
  pseudonymId: string;
  ownerUserId?: string | null;
  einwilligungAt?: string | null;
  einwilligungVersion?: string | null;
  kontaktart?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  kontaktzeitraum?: string | null;
  vorname?: string | null;
  nachname?: string | null;
  telefon?: string | null;
  email?: string | null;
  adresse?: string | null;
  beratungsstelle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angebote".
 */
export interface Angebote {
  id: string;
  bedarfPseudonymId: string;
  tenantId: string;
  nachricht?: string | null;
  mehrwegMin?: number | null;
  status?: ('abgegeben' | 'zurueckgezogen') | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zahlungen".
 */
export interface Zahlungen {
  id: string;
  art: 'express' | 'gebuehr' | 'abo';
  status: 'offen' | 'bezahlt' | 'fehlgeschlagen' | 'storniert' | 'abgelaufen';
  betragCents: number;
  waehrung?: string | null;
  beschreibung?: string | null;
  bedarfId?: string | null;
  tenantId?: string | null;
  molliePaymentId?: string | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abos".
 */
export interface Abo {
  id: string;
  tenantId: string;
  stufe: 'klein' | 'mittel' | 'gross';
  monatlichCents: number;
  status: 'ausstehend' | 'aktiv' | 'gekuendigt' | 'fehlgeschlagen';
  mollieCustomerId?: string | null;
  mollieSubscriptionId?: string | null;
  firstPaymentId?: string | null;
  activatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "praeventionsempfehlungen".
 */
export interface Praeventionsempfehlungen {
  id: string;
  pseudonymId: string;
  tenantId: string;
  status?: ('entwurf' | 'finalisiert') | null;
  felder?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  empfehlungen?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  freitext?: string | null;
  erstelltVon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'klienten_identitaet';
        value: string | KlientenIdentitaet;
      } | null)
    | ({
        relationTo: 'klienten_operativ';
        value: string | KlientenOperativ;
      } | null)
    | ({
        relationTo: 'touren';
        value: string | Touren;
      } | null)
    | ({
        relationTo: 'gdpr_audit_log';
        value: string | GdprAuditLog;
      } | null)
    | ({
        relationTo: 'bedarfe';
        value: string | Bedarfe;
      } | null)
    | ({
        relationTo: 'angehoerige_identitaet';
        value: string | AngehoerigeIdentitaet;
      } | null)
    | ({
        relationTo: 'angebote';
        value: string | Angebote;
      } | null)
    | ({
        relationTo: 'zahlungen';
        value: string | Zahlungen;
      } | null)
    | ({
        relationTo: 'abos';
        value: string | Abo;
      } | null)
    | ({
        relationTo: 'praeventionsempfehlungen';
        value: string | Praeventionsempfehlungen;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenantId?: T;
  totpSecret?: T;
  totpEnabled?: T;
  dienstName?: T;
  einzugsGeo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  einzugsRadiusKm?: T;
  einwilligungAt?: T;
  einwilligungVersion?: T;
  suchendeTyp?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "klienten_identitaet_select".
 */
export interface KlientenIdentitaetSelect<T extends boolean = true> {
  pseudonymId?: T;
  tenantId?: T;
  externalId?: T;
  vorname?: T;
  nachname?: T;
  adresse?: T;
  telefon?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "klienten_operativ_select".
 */
export interface KlientenOperativSelect<T extends boolean = true> {
  pseudonymId?: T;
  tenantId?: T;
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  pflegegrad?: T;
  leistungen?: T;
  qualifikation?: T;
  zeitfenster?:
    | T
    | {
        von?: T;
        bis?: T;
      };
  dauerMin?: T;
  kostentraegerArt?: T;
  krankenversicherer?: T;
  bezugspflege?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "touren_select".
 */
export interface TourenSelect<T extends boolean = true> {
  tenantId?: T;
  datum?: T;
  pflegekraftId?: T;
  pflegekraftQualifikation?: T;
  start?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  ende?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  startZeit?: T;
  einsaetze?:
    | T
    | {
        pseudonymId?: T;
        geo?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
        zeitfenster?:
          | T
          | {
              von?: T;
              bis?: T;
            };
        dauerMin?: T;
        grundzeitMin?: T;
        qualifikation?: T;
        ankunft?: T;
        probe?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gdpr_audit_log_select".
 */
export interface GdprAuditLogSelect<T extends boolean = true> {
  timestamp?: T;
  request_type?: T;
  identity_hash?: T;
  pepper_version?: T;
  former_pseudonym_id?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bedarfe_select".
 */
export interface BedarfeSelect<T extends boolean = true> {
  pseudonymId?: T;
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  pflegegrad?: T;
  leistungen?: T;
  qualifikation?: T;
  kostentraegerArt?: T;
  krankenversicherer?: T;
  bundesland?: T;
  stadtteil?: T;
  alter?: T;
  wohnsituation?: T;
  startDatum?: T;
  abwesenheiten?: T;
  abwesenheitErlaeuterung?: T;
  besonderheiten?: T;
  leistungsauswahl?: T;
  zeitfenster?:
    | T
    | {
        von?: T;
        bis?: T;
      };
  dauerMin?: T;
  grundzeitMin?: T;
  express?: T;
  status?: T;
  matchingTenants?: T;
  selectedTenantId?: T;
  deadlineAt?: T;
  firstResponseAt?: T;
  uebernommenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angehoerige_identitaet_select".
 */
export interface AngehoerigeIdentitaetSelect<T extends boolean = true> {
  pseudonymId?: T;
  ownerUserId?: T;
  einwilligungAt?: T;
  einwilligungVersion?: T;
  kontaktart?: T;
  kontaktzeitraum?: T;
  vorname?: T;
  nachname?: T;
  telefon?: T;
  email?: T;
  adresse?: T;
  beratungsstelle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angebote_select".
 */
export interface AngeboteSelect<T extends boolean = true> {
  bedarfPseudonymId?: T;
  tenantId?: T;
  nachricht?: T;
  mehrwegMin?: T;
  status?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zahlungen_select".
 */
export interface ZahlungenSelect<T extends boolean = true> {
  art?: T;
  status?: T;
  betragCents?: T;
  waehrung?: T;
  beschreibung?: T;
  bedarfId?: T;
  tenantId?: T;
  molliePaymentId?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abos_select".
 */
export interface AbosSelect<T extends boolean = true> {
  tenantId?: T;
  stufe?: T;
  monatlichCents?: T;
  status?: T;
  mollieCustomerId?: T;
  mollieSubscriptionId?: T;
  firstPaymentId?: T;
  activatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "praeventionsempfehlungen_select".
 */
export interface PraeventionsempfehlungenSelect<T extends boolean = true> {
  pseudonymId?: T;
  tenantId?: T;
  status?: T;
  felder?: T;
  empfehlungen?: T;
  freitext?: T;
  erstelltVon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}